version: '3.7'

services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres
    volumes:
      - ./keycloak-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db

  mongo:
    container_name: mongo
    image: mongo:6.0
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
